version: '3.1'
services:
  ewm-stats-db:
    image: postgres:13.7
    container_name: ewm-stats-db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmstats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver

  stats-server:
    build: ./ewm-stats/stats-server/
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/ewmstats
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver

  ewm-service-db:
    image: postgres:13.7
    container_name: ewm-service-db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-service/
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service-db
    environment:
      - STATS_CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service-db:5432/ewmservice
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
